server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wyoung163/config-file.git
          clone-on-start: true
          search-paths: /**
          default-label: main
          username: ""
          password: ""
    kafka:
      bootstrap-severs: localhost:9092
    bus:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"